# https://github.com/yeasy/docker-compose-files/tree/master/hyperledger
# This compose file will start a Hyperledger Fabric 1.0 MVE, including
# * ca
# * orderer
# * peer
# * sdk for testing

version: '2.0'

services:
  ca:
    image: hyperledger/fabric-ca:1.2.0
    container_name: ca
    hostname: ca
    ports:
      - "8888:8888"
      - "7054:7054"
    command: fabric-ca-server start -b admin:adminpw

  orderer:
    image: hyperledger/fabric-orderer:1.2.0
    container_name: orderer
    hostname: orderer0.example.com
    environment:
        - ORDERER_GENERAL_LEDGERTYPE=file
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_LISTENPORT=7050
        - CONFIGTX_ORDERER_ORDERERTYPE=solo
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    volumes:
        - ../crypto-config/ordererOrganizations/example.com/peers/orderer0.example.com/msp:/var/hyperledger/msp
        - ../crypto-config/ordererOrganizations/example.com/peers/orderer0.example.com/tls:/var/hyperledger/tls
        - ../genesis_block.pb:/var/hyperledger/orderer/orderer.genesis.block
    ports:
      - "7050:7050"
    command: orderer

  couchdb:
    container_name: couchdb
    hostname: couchdb
    image: hyperledger/fabric-couchdb:0.4.10
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"

  peer0:
    extends:
      file: peer.yml
      service: peer
    container_name: peer0
    hostname: peer0.org1.example.com
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=org1.example.com
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    volumes:
      - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/msp
      - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/tls
      - ../crypto-config/peerOrganizations/org1.example.com/users:/var/hyperledger/users
    links:
      - ca
      - orderer
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - ca
      - orderer
      - couchdb

#networks:
#  default:
#    external:
#      name: hyperledger_fabric
