# https://github.com/yeasy/docker-compose-files/tree/master/hyperledger
# This compose file will start a Hyperledger Fabric 1.0 MVE, including
# * ca
# * orderer
# * peer
# * sdk for testing

version: '2.0'

services:
  ca.org1.example.com:
    image: hyperledger/fabric-ca:1.3.0
    container_name: ca.org1.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/154c7e3e7891582272f2c5d3069d1d14882e815e14ca210e18ed235766999345_sk
    ports:
      - "8888:8888"
      - "7054:7054"
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    command: fabric-ca-server start -b admin:adminpw

  orderer.example.com:
    image: hyperledger/fabric-orderer:1.3.0
    container_name: orderer.example.com
    environment:
        - ORDERER_GENERAL_LEDGERTYPE=file
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_LISTENPORT=7050
        - CONFIGTX_ORDERER_ORDERERTYPE=solo
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_LOGLEVEL=info
        - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
        - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
        - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    volumes:
        - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com:/etc/hyperledger/msp/orderer
        - ./genesis_block.pb:/var/hyperledger/orderer/orderer.genesis.block
    ports:
      - "7050:7050"
    command: orderer

  couchdb.peer0.org1.example.com:
    container_name: couchdb.peer0.org1.example.com
    image: hyperledger/fabric-couchdb:0.4.14
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:1.3.0
    container_name: peer0.org1.example.com
    environment:
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.org1.example.com:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com:/etc/hyperledger/msp/peer
    links:
      - orderer.example.com
      - couchdb.peer0.org1.example.com
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - ca.org1.example.com
      - orderer.example.com
      - couchdb.peer0.org1.example.com

#networks:
#  default:
#    external:
#      name: hyperledger_fabric
