# https://github.com/yeasy/docker-compose-files/tree/master/hyperledger
# This compose file will start a Hyperledger Fabric 1.0 MVE, including
# * ca
# * orderer
# * peer
# * sdk for testing

version: '2.0'

services:
  orderer:
    image: hyperledger/fabric-orderer:1.3.0
    container_name: orderer
    environment:
        - ORDERER_GENERAL_LEDGERTYPE=file
        - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
        - ORDERER_GENERAL_LISTENPORT=7050
        - CONFIGTX_ORDERER_ORDERERTYPE=solo
        - ORDERER_GENERAL_GENESISMETHOD=file
        - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
    volumes:
        - ../genesis_block.pb:/var/hyperledger/orderer/orderer.genesis.block
    ports:
      - "7050:7050"
    command: orderer

  couchdb:
    container_name: couchdb
    image: hyperledger/fabric-couchdb:0.4.14
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"

  peer0:
    extends:
      file: peer.yml
      service: peer
    container_name: peer0
    environment:
      #- CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=SampleOrg
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb:5984
    links:
      - orderer
      - couchdb
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer
      - couchdb

#networks:
#  default:
#    external:
#      name: hyperledger_fabric
